// Builds public/recipes.json from: (a) the 21 hand-written original recipes,
// and (b) a larger set generated by combining a real-ingredient database with
// cooking-method templates, so the app has 100+ distinct, still-detailed dishes
// without the data living inside the JS bundle. Run with: node scripts/generate-recipes.mjs
import { writeFileSync } from 'node:fs';

// ---------------------------------------------------------------------------
// 1. The 21 original hand-written recipes (unchanged, full quality)
// ---------------------------------------------------------------------------
const HANDWRITTEN = [
  { id: 'r1', name: 'Puré de calabaza y patata', mealTypes: ['comida'], minAgeIdx: 0, allergens: [], time: 20, texture: 'pure', foodGroups: ['verduras'],
    ingredients: [
      { name: 'Calabaza', quantity: '1/4 de calabaza pequeña, pelada y sin pepitas (unos 200 g)' },
      { name: 'Patata', quantity: '1 patata mediana, pelada (unos 150 g)' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita (unos 5 ml)' },
    ],
    utensils: ['Cazuela mediana', 'Colador', 'Batidora de mano (o un tenedor)', 'Tabla y cuchillo'],
    steps: [
      'Lávate las manos y lava bien la calabaza y la patata bajo el grifo, aunque las vayas a pelar.',
      'Pela la calabaza y la patata con un pelador o un cuchillo pequeño. Retira las pepitas de la calabaza con una cuchara. Corta ambas en dados de unos 2 cm: así se cuecen antes y de forma pareja.',
      'Pon los dados en la cazuela y cúbrelos con agua fría sin sal (el bebé no necesita sal añadida). Lleva a ebullición y luego baja el fuego para que hierva suave.',
      'Cuece unos 15 minutos, hasta que puedas atravesar un trozo de patata con un tenedor sin resistencia. Si aún está duro, dale 3-4 minutos más.',
      'Escurre con el colador, reservando un par de cucharadas del agua de cocción por si necesitas aclarar el puré después.',
      'Tritura con la batidora (o chafa con el tenedor si prefieres una textura menos fina) junto con el aceite de oliva, añadiendo un poco del agua reservada hasta lograr una crema suave y sin grumos.',
      'Deja templar y comprueba la temperatura con una cucharita antes de dárselo: debe estar tibio, nunca caliente.',
    ],
    tips: [
      'Puedes preparar el doble de cantidad y congelar el resto en cubiteras; se conserva bien hasta 1 mes.',
      'Si es la primera vez que tu bebé prueba la calabaza, ofrécela sola 2-3 días antes de mezclarla con otros alimentos nuevos, para poder identificar posibles reacciones.',
    ],
  },
  { id: 'r2', name: 'Lentejas con verduras', mealTypes: ['comida'], minAgeIdx: 1, allergens: [], time: 35, texture: 'pure', foodGroups: ['legumbres', 'verduras'],
    ingredients: [
      { name: 'Lentejas', quantity: '3 cucharadas soperas secas (unos 40 g)' },
      { name: 'Zanahoria', quantity: '1/2 zanahoria, pelada' },
      { name: 'Puerro', quantity: '1/2 puerro (solo la parte blanca y verde clara)' },
      { name: 'Patata', quantity: '1/2 patata pequeña, pelada' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Cazuela', 'Colador', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Lava las lentejas bajo el grifo en un colador hasta que el agua salga clara; así eliminas el polvo y posibles impurezas.',
      'Lava y pela la zanahoria y la patata. Lava bien el puerro separando las capas, ya que suele acumular tierra entre ellas, y córtalo en rodajas finas. Corta la zanahoria y la patata en dados pequeños.',
      'Pon las lentejas y las verduras en la cazuela y cubre con agua fría sin sal, un par de dedos por encima de los ingredientes.',
      'Lleva a ebullición, baja el fuego y cuece a fuego lento unos 30 minutos, removiendo de vez en cuando y retirando la espuma que suba a la superficie.',
      'Comprueba el punto apretando una lenteja entre los dedos: debe deshacerse sin esfuerzo. Si siguen duras, añade un poco más de agua caliente y cuece 5-10 minutos más.',
      'Escurre reservando un poco del caldo de cocción y tritura con la batidora junto con el aceite de oliva, añadiendo caldo hasta conseguir la textura que tu bebé tolere.',
      'Deja templar y comprueba la temperatura antes de servir.',
    ],
    tips: ['Las legumbres cocidas y trituradas se congelan muy bien: guarda raciones individuales para los días con poco tiempo.'],
  },
  { id: 'r3', name: 'Crema de calabacín y pollo', mealTypes: ['comida'], minAgeIdx: 0, allergens: [], time: 25, texture: 'pure', foodGroups: ['verduras', 'proteina'],
    ingredients: [
      { name: 'Calabacín', quantity: '1/2 calabacín pequeño' },
      { name: 'Pechuga de pollo', quantity: '1 filete pequeño (unos 60 g)' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Cazuela', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Lava el calabacín (no hace falta pelarlo si la piel está en buen estado, aporta fibra) y córtalo en dados. Corta la pechuga de pollo en trozos pequeños, retirando cualquier resto de grasa o piel.',
      'Pon el calabacín y el pollo en la cazuela y cubre con agua sin sal.',
      'Lleva a ebullición y cuece a fuego medio 20 minutos, hasta que el pollo esté blanco por dentro, sin ninguna parte rosada, y el calabacín se deshaga al pincharlo.',
      'Escurre reservando un poco del caldo de cocción.',
      'Tritura el pollo y el calabacín juntos con la batidora, añadiendo caldo poco a poco hasta lograr una crema fina, sin grumos ni hebras.',
      'Añade el aceite de oliva en crudo justo antes de servir y remueve bien.',
      'Deja templar y comprueba que no queden trozos duros de pollo sin triturar antes de ofrecerlo.',
    ],
    tips: ['Comprueba siempre que el pollo esté completamente cocido, sin ninguna parte rosada, antes de triturarlo.'],
  },
  { id: 'r4', name: 'Arroz con verduras y pollo', mealTypes: ['comida'], minAgeIdx: 2, allergens: [], time: 30, texture: 'trocitos', foodGroups: ['cereales', 'verduras', 'proteina'],
    ingredients: [
      { name: 'Arroz', quantity: '3 cucharadas soperas (unos 40 g)' },
      { name: 'Zanahoria', quantity: '1/2 zanahoria pequeña, en dados' },
      { name: 'Guisantes', quantity: '2 cucharadas (frescos o congelados)' },
      { name: 'Pechuga de pollo', quantity: '1 filete pequeño (unos 60 g)' },
    ],
    utensils: ['Cazuela para el arroz', 'Sartén con tapa', 'Colador', 'Tabla y cuchillo'],
    steps: [
      'Lava el arroz bajo el grifo hasta que el agua salga clara. Cuécelo en agua sin sal siguiendo el tiempo del paquete (suele ser 15-18 minutos). Escurre y reserva.',
      'Mientras se cuece el arroz, pela y corta la zanahoria en dados muy pequeños (de menos de 1 cm) y corta la pechuga de pollo en tiras finas.',
      'Calienta un chorrito de aceite en una sartén y saltea el pollo a fuego medio 5-6 minutos, removiendo, hasta que esté dorado y bien hecho por dentro.',
      'Añade la zanahoria y los guisantes a la sartén con un par de cucharadas de agua, tapa y cocina 8-10 minutos hasta que la zanahoria esté blanda al pincharla.',
      'Mezcla el arroz cocido con el pollo y las verduras en la sartén y remueve 1-2 minutos a fuego bajo para que se integren los sabores.',
      'Con un tenedor, aplasta ligeramente los guisantes y separa los granos de arroz para que no formen bolas: así es más fácil de masticar y tragar para tu bebé.',
      'Deja templar y sirve en trozos pequeños y blandos, comprobando que no haya piezas duras.',
    ],
    tips: ['Si tu bebé todavía no mastica bien, puedes triturar ligeramente la mezcla con un tenedor en vez de dejarla entera.'],
  },
  { id: 'r5', name: 'Puré de garbanzos y zanahoria', mealTypes: ['comida'], minAgeIdx: 1, allergens: [], time: 35, texture: 'pure', foodGroups: ['legumbres', 'verduras'],
    ingredients: [
      { name: 'Garbanzos cocidos', quantity: '4 cucharadas (unos 80 g)' },
      { name: 'Zanahoria', quantity: '1/2 zanahoria, pelada' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Cazuela', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Pela y corta la zanahoria en rodajas finas para que se cueza antes.',
      'Ponla en la cazuela y cubre con agua sin sal. Lleva a ebullición y cuece 12-15 minutos, hasta que esté blanda al pinchar con un tenedor.',
      'Si usas garbanzos de bote, escúrrelos y enjuágalos bajo el grifo para eliminar el exceso de sal del líquido de conserva; si los has cocido en casa, resérvalos sin más.',
      'Añade los garbanzos a la cazuela con la zanahoria durante los últimos 2-3 minutos, solo para calentarlos.',
      'Escurre reservando un poco de agua de cocción y tritura todo junto con la batidora y el aceite de oliva.',
      'Añade agua reservada poco a poco hasta conseguir una crema fina; los garbanzos pueden dejar textura granulada, tritura bien si tu bebé aún no tolera grumos.',
      'Deja templar antes de servir.',
    ],
    tips: ['La piel de los garbanzos puede quedar en trocitos pequeños tras triturar: si tu bebé es muy pequeño, pasa el puré por un colador fino para eliminarla.'],
  },
  { id: 'r6', name: 'Merluza con puré de patata y brócoli', mealTypes: ['comida'], minAgeIdx: 1, allergens: ['pescado'], time: 25, texture: 'pure', foodGroups: ['proteina', 'verduras'],
    ingredients: [
      { name: 'Merluza', quantity: '1 lomo pequeño, sin piel ni espinas visibles (unos 60 g)' },
      { name: 'Patata', quantity: '1 patata mediana, pelada' },
      { name: 'Brócoli', quantity: '3-4 ramilletes pequeños' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Vaporera (o cazuela con cestillo)', 'Cazuela', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Pela y trocea la patata en dados. Separa el brócoli en ramilletes pequeños y lava bien.',
      'Cuece la patata en agua sin sal unos 15 minutos hasta que esté blanda. Añade el brócoli los últimos 6-7 minutos.',
      'Mientras tanto, cocina la merluza al vapor (o en una sartén con un poco de agua, tapada) 6-8 minutos, hasta que la carne quede blanca y se separe fácilmente en láminas con el tenedor.',
      'Este es el paso más importante: desmenuza la merluza con los dedos limpios o dos tenedores y repasa cada trozo despacio buscando espinas. La merluza suele tener pocas, pero conviene revisar bien antes de triturar.',
      'Escurre la patata y el brócoli reservando un poco del agua de cocción.',
      'Tritura la merluza sin espinas junto con la patata, el brócoli y el aceite de oliva, añadiendo agua reservada hasta lograr una crema suave.',
      'Vuelve a repasar el puré ya triturado con los dedos limpios por si quedara alguna espina pequeña, antes de ofrecerlo.',
    ],
    tips: ['El pescado es un alérgeno frecuente: si es la primera vez que lo prueba, ofrécelo en pequeña cantidad por la mañana, para poder observar cómo reacciona durante el día.'],
  },
  { id: 'r7', name: 'Ternera guisada con verduras', mealTypes: ['comida'], minAgeIdx: 2, allergens: [], time: 40, texture: 'trocitos', foodGroups: ['proteina', 'verduras'],
    ingredients: [
      { name: 'Ternera', quantity: '60-70 g para guisar, en trozos pequeños' },
      { name: 'Zanahoria', quantity: '1/2 zanahoria, pelada' },
      { name: 'Tomate', quantity: '1 tomate maduro pequeño' },
      { name: 'Patata', quantity: '1/2 patata pequeña, pelada' },
    ],
    utensils: ['Cazuela u olla', 'Tabla y cuchillo'],
    steps: [
      'Corta la ternera en trozos muy pequeños, del tamaño de un guisante grande, retirando cualquier nervio o grasa visible.',
      'Calienta un chorrito de aceite de oliva en la cazuela y sofríe la ternera a fuego medio 3-4 minutos, removiendo, hasta que cambie de color por fuera.',
      'Pela y corta la zanahoria y la patata en dados pequeños. Pela y trocea el tomate (puedes escaldarlo unos segundos en agua caliente para que la piel salga con facilidad).',
      'Añade las verduras a la cazuela con la ternera y cubre con agua sin sal hasta que todo quede cubierto.',
      'Tapa y cocina a fuego lento 30 minutos, removiendo de vez en cuando y añadiendo un poco más de agua si se queda seco.',
      'Comprueba que la ternera esté muy tierna deshaciéndola con un tenedor; si aún está dura, dale 10-15 minutos más a fuego bajo.',
      'Deja templar y, si tu bebé empieza con trocitos, aplasta ligeramente cada pieza con el tenedor para facilitar la masticación.',
    ],
    tips: ['La ternera guisada muy despacio queda más tierna: si tienes tiempo, cocínala 45-50 minutos a fuego muy bajo para que se deshaga con facilidad.'],
  },
  { id: 'r8', name: 'Tortilla de calabacín', mealTypes: ['comida'], minAgeIdx: 2, allergens: ['huevo'], time: 15, texture: 'finger', foodGroups: ['proteina', 'verduras'],
    ingredients: [
      { name: 'Huevo', quantity: '1 unidad' },
      { name: 'Calabacín', quantity: '1/2 calabacín pequeño, rallado' },
      { name: 'Aceite de oliva virgen extra', quantity: 'Unas gotas' },
    ],
    utensils: ['Rallador', 'Bol', 'Sartén antiadherente', 'Espátula'],
    steps: [
      'Lava el calabacín y rállalo con la piel usando un rallador de agujero grueso.',
      'Pon el calabacín rallado en un colador o sobre papel de cocina y presiona para quitar el exceso de agua; así la tortilla no quedará blanda.',
      'Casca el huevo en un bol (revisa que no caiga nada de cáscara dentro) y bátelo bien con un tenedor.',
      'Mezcla el calabacín escurrido con el huevo batido.',
      'Calienta una gota de aceite en una sartén antiadherente a fuego medio-bajo. Vierte la mezcla y extiéndela para formar una tortilla fina.',
      'Cocina 3-4 minutos por un lado hasta que los bordes estén cuajados, dale la vuelta con ayuda de un plato y cocina 2-3 minutos más por el otro lado, hasta que el centro esté totalmente cuajado, sin huevo líquido.',
      'Deja templar sobre una tabla y corta en tiras del grosor de un dedo adulto, para que tu bebé pueda sujetarlas con el puño.',
    ],
    tips: [
      'Comprueba siempre que el huevo esté completamente cuajado, sin partes líquidas, antes de servirlo.',
      'El huevo es un alérgeno frecuente: si es la primera vez, ofrece un trozo pequeño y observa a tu bebé durante las horas siguientes.',
    ],
  },
  { id: 'r9', name: 'Puré de lentejas rojas con calabaza', mealTypes: ['comida'], minAgeIdx: 0, allergens: [], time: 25, texture: 'pure', foodGroups: ['legumbres', 'verduras'],
    ingredients: [
      { name: 'Lentejas rojas', quantity: '3 cucharadas soperas (unos 40 g)' },
      { name: 'Calabaza', quantity: '1/4 de calabaza pequeña, pelada y sin pepitas' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Cazuela', 'Colador', 'Batidora de mano'],
    steps: [
      'Enjuaga las lentejas rojas en un colador bajo el grifo hasta que el agua salga clara (se cuecen rápido y no necesitan remojo previo).',
      'Pela la calabaza, retira las pepitas con una cuchara y córtala en dados pequeños.',
      'Pon las lentejas y la calabaza en la cazuela y cubre con agua fría sin sal.',
      'Lleva a ebullición, baja el fuego y cuece 18-20 minutos, removiendo de vez en cuando, hasta que las lentejas estén completamente deshechas y blandas.',
      'Comprueba el punto aplastando una lenteja entre los dedos: debe deshacerse sin esfuerzo.',
      'Escurre el exceso de agua si quedara mucho líquido y tritura todo junto con el aceite de oliva hasta obtener una crema fina y homogénea.',
      'Deja templar antes de servir.',
    ],
    tips: ['Las lentejas rojas se deshacen solas al cocer, así que este puré suele quedar muy cremoso sin apenas necesidad de triturar.'],
  },
  { id: 'r10', name: 'Plátano chafado con copos de avena', mealTypes: ['merienda'], minAgeIdx: 0, allergens: [], time: 5, texture: 'pure', foodGroups: ['frutas', 'cereales'],
    ingredients: [
      { name: 'Plátano', quantity: '1 unidad, bien maduro' },
      { name: 'Copos de avena finos', quantity: '1 cucharada' },
    ],
    utensils: ['Bol', 'Tenedor'],
    steps: [
      'Elige un plátano bien maduro, con alguna mancha marrón en la piel: es más dulce y fácil de chafar.',
      'Pela el plátano y ponlo en un bol.',
      'Chafa con un tenedor hasta obtener una pasta sin grumos grandes.',
      'Añade los copos de avena finos poco a poco, removiendo, hasta que se integren y la mezcla espese ligeramente.',
      'Deja reposar 2-3 minutos: la avena absorbe algo de humedad y la textura queda más suave.',
      'Remueve una última vez antes de servir; si queda muy espeso, añade unas gotas de agua para aligerar.',
    ],
    tips: [
      'No necesita cocción, así que es ideal para cuando tienes poco tiempo.',
      'Si usas copos de avena normales (no finos), tritúralos unos segundos en un molinillo para que sean más fáciles de digerir.',
    ],
  },
  { id: 'r11', name: 'Yogur natural con fruta', mealTypes: ['merienda'], minAgeIdx: 1, allergens: ['lacteos'], time: 5, texture: 'trocitos', foodGroups: ['lacteos', 'frutas'],
    ingredients: [
      { name: 'Yogur natural sin azúcar', quantity: '1 unidad (125 g)' },
      { name: 'Pera o manzana', quantity: '1/2 unidad, madura' },
    ],
    utensils: ['Tabla y cuchillo pequeño', 'Bol'],
    steps: [
      'Lava bien la pera o la manzana. Puedes pelarla o dejar la piel si está bien lavada, según lo que tolere tu bebé.',
      'Corta la fruta en trozos muy pequeños y blandos; si está dura, cuécela al vapor 5 minutos para ablandarla antes de trocearla.',
      'Pon el yogur natural sin azúcar añadido en un bol.',
      'Mezcla los trozos de fruta con el yogur, removiendo bien.',
      'Sirve a temperatura ambiente, nunca recién sacado de la nevera, para que no esté demasiado frío para tu bebé.',
    ],
    tips: [
      'Elige siempre yogur natural sin azúcar ni edulcorantes añadidos: los yogures "para niños" suelen llevar más azúcar del recomendado.',
      'El yogur es lácteo: si es la primera vez que tu bebé prueba lácteos de vaca, empieza con una cantidad pequeña.',
    ],
  },
  { id: 'r12', name: 'Tortitas de avena y plátano', mealTypes: ['merienda'], minAgeIdx: 2, allergens: ['huevo'], time: 15, texture: 'finger', foodGroups: ['cereales', 'frutas'],
    ingredients: [
      { name: 'Avena', quantity: '3 cucharadas (unos 30 g)' },
      { name: 'Plátano', quantity: '1 unidad, madura' },
      { name: 'Huevo', quantity: '1 unidad' },
    ],
    utensils: ['Batidora (o un tenedor)', 'Bol', 'Sartén antiadherente', 'Espátula'],
    steps: [
      'Pela el plátano y trocéalo. Casca el huevo en un bol comprobando que no caiga nada de cáscara.',
      'Tritura la avena, el plátano y el huevo juntos con la batidora hasta obtener una masa homogénea sin grumos grandes (o chafa el plátano con un tenedor y mezcla bien si no tienes batidora).',
      'Calienta una sartén antiadherente a fuego bajo sin aceite (o con una gota si tiende a pegarse).',
      'Vierte pequeñas porciones de masa, una cucharada cada vez, para formar tortitas pequeñas.',
      'Cocina 2 minutos por un lado hasta que salgan burbujas en la superficie y los bordes se vean firmes, luego dale la vuelta con la espátula y cocina 1-2 minutos más por el otro lado.',
      'Comprueba que el centro esté bien cuajado, sin masa líquida, antes de retirarlas del fuego.',
      'Deja enfriar sobre un plato y corta en tiras para que tu bebé las pueda coger con la mano.',
    ],
    tips: [
      'Haz tortitas pequeñas, del tamaño de una cuchara sopera, para que se cocinen bien por dentro sin quemarse por fuera.',
      'Este plato lleva huevo: si es la primera vez que lo prueba, ofrece una cantidad pequeña y observa a tu bebé un par de horas.',
    ],
  },
  { id: 'r13', name: 'Puré de manzana y pera', mealTypes: ['merienda'], minAgeIdx: 0, allergens: [], time: 15, texture: 'pure', foodGroups: ['frutas'],
    ingredients: [
      { name: 'Manzana', quantity: '1 unidad' },
      { name: 'Pera', quantity: '1 unidad' },
    ],
    utensils: ['Vaporera (o cazuela con cestillo)', 'Batidora de mano (o un tenedor)'],
    steps: [
      'Lava, pela y descorazona la manzana y la pera. Córtalas en trozos de tamaño similar para que se cuezan por igual.',
      'Colócalas en una vaporera o en una cazuela con un dedo de agua.',
      'Cuece al vapor unos 10 minutos, hasta que un cuchillo entre en la fruta sin resistencia.',
      'Retira del fuego y deja templar unos minutos.',
      'Tritura con la batidora (o chafa con un tenedor si prefieres una textura más rústica) hasta obtener una compota fina.',
      'Si queda demasiado espesa, añade una cucharadita del agua de cocción reservada.',
    ],
    tips: [
      'No hace falta añadir azúcar: la fruta cocida ya tiene un sabor dulce natural.',
      'Se conserva bien en la nevera 2 días en un recipiente cerrado, o congelada hasta 1 mes.',
    ],
  },
  { id: 'r14', name: 'Palitos de pan con aguacate', mealTypes: ['merienda'], minAgeIdx: 2, allergens: ['gluten'], time: 5, texture: 'finger', foodGroups: ['cereales', 'grasas'],
    ingredients: [
      { name: 'Pan tierno', quantity: '1 rebanada, a poder ser integral' },
      { name: 'Aguacate', quantity: '1/2 unidad, madura' },
    ],
    utensils: ['Tabla y cuchillo', 'Bol', 'Tenedor'],
    steps: [
      'Corta el pan en palitos de aproximadamente 1 cm de grosor y del largo de un dedo adulto, para que tu bebé pueda sujetarlos bien con el puño.',
      'Parte el aguacate por la mitad, retira el hueso con cuidado y extrae la pulpa con una cuchara.',
      'Chafa la pulpa con un tenedor en un bol hasta obtener una crema suave, sin grumos grandes.',
      'Unta generosamente cada palito de pan con la crema de aguacate por todas las caras.',
      'Sirve enseguida: el aguacate se oxida y oscurece rápido al contacto con el aire.',
    ],
    tips: [
      'Elige un aguacate maduro, que ceda ligeramente al presionarlo con el dedo, para que sea fácil de chafar.',
      'Este plato lleva gluten (el pan): si es la primera vez que lo prueba, empieza con una cantidad pequeña.',
    ],
  },
  { id: 'r15', name: 'Compota de melocotón', mealTypes: ['merienda'], minAgeIdx: 0, allergens: [], time: 15, texture: 'pure', foodGroups: ['frutas'],
    ingredients: [{ name: 'Melocotón', quantity: '1-2 unidades, maduras' }],
    utensils: ['Cazuela', 'Batidora de mano (o un tenedor)'],
    steps: [
      'Lava el melocotón. Puedes escaldarlo unos segundos en agua hirviendo y pasarlo después por agua fría: así la piel se retira mucho más fácil.',
      'Pela, deshuesa y corta el melocotón en trozos.',
      'Ponlo en la cazuela con un par de cucharadas de agua (la fruta suelta líquido al cocerse, no hace falta cubrirla del todo).',
      'Cuece a fuego bajo 10 minutos, removiendo de vez en cuando, hasta que los trozos estén blandos y se deshagan con facilidad.',
      'Retira del fuego y deja templar.',
      'Tritura con la batidora o chafa con un tenedor hasta lograr una compota suave y sin trozos.',
    ],
    tips: ['Si el melocotón está muy maduro y dulce, puedes saltarte la cocción y triturarlo directamente en crudo.'],
  },
  { id: 'r16', name: 'Crema de puerro y patata', mealTypes: ['cena'], minAgeIdx: 0, allergens: [], time: 25, texture: 'pure', foodGroups: ['verduras'],
    ingredients: [
      { name: 'Puerro', quantity: '1/2 unidad (parte blanca y verde clara)' },
      { name: 'Patata', quantity: '1 patata mediana, pelada' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Cazuela', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Corta el puerro por la mitad a lo largo y lávalo bien bajo el grifo separando las capas, ya que suele acumular tierra entre ellas. Corta la parte blanca y verde clara en rodajas finas.',
      'Pela y corta la patata en dados.',
      'Pon el puerro y la patata en la cazuela y cubre con agua sin sal.',
      'Lleva a ebullición, baja el fuego y cuece 20 minutos, hasta que la patata se deshaga al pincharla con un tenedor.',
      'Escurre reservando un poco del caldo de cocción.',
      'Tritura con la batidora junto con el aceite de oliva, añadiendo caldo poco a poco hasta lograr una crema fina y sin hebras de puerro.',
      'Deja templar y comprueba que no queden hebras sin triturar antes de servir.',
    ],
    tips: ['Congela en raciones pequeñas: esta crema aguanta bien hasta 1 mes en el congelador.'],
  },
  { id: 'r17', name: 'Puré de brócoli y pescado blanco', mealTypes: ['cena'], minAgeIdx: 1, allergens: ['pescado'], time: 20, texture: 'pure', foodGroups: ['verduras', 'proteina'],
    ingredients: [
      { name: 'Brócoli', quantity: '3-4 ramilletes pequeños' },
      { name: 'Pescado blanco', quantity: '1 lomo pequeño, sin piel ni espinas visibles (unos 60 g)' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Vaporera', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Separa el brócoli en ramilletes pequeños y lávalos bien.',
      'Cuece el brócoli al vapor 8-10 minutos, hasta que esté blando al pincharlo con un tenedor.',
      'Cocina el pescado blanco al vapor (o en una sartén con un poco de agua, tapado) 5-7 minutos, hasta que la carne quede opaca y se deshaga en láminas con facilidad.',
      'Con los dedos limpios, desmenuza el pescado y repasa cada trozo despacio, buscando espinas. Este paso es el más importante: no te precipites.',
      'Tritura el pescado sin espinas junto con el brócoli y el aceite de oliva, añadiendo un poco de agua si queda muy espeso.',
      'Vuelve a repasar el puré ya triturado con los dedos limpios, por si quedara alguna espina pequeña.',
      'Deja templar antes de servir.',
    ],
    tips: [
      'Pide en la pescadería que te quiten la piel y las espinas visibles; aun así, repasa siempre tú misma/o antes de dárselo a tu bebé.',
      'El pescado es un alérgeno frecuente: introdúcelo poco a poco y por la mañana, para poder observar cómo reacciona.',
    ],
  },
  { id: 'r18', name: 'Sopa de fideos con verduras', mealTypes: ['cena'], minAgeIdx: 2, allergens: ['gluten'], time: 20, texture: 'trocitos', foodGroups: ['cereales', 'verduras'],
    ingredients: [
      { name: 'Fideos finos', quantity: 'Un puñado pequeño (unos 30 g)' },
      { name: 'Zanahoria', quantity: '1/2 zanahoria, en dados pequeños' },
      { name: 'Calabacín', quantity: '1/2 calabacín pequeño, en dados pequeños' },
    ],
    utensils: ['Cazuela', 'Tabla y cuchillo'],
    steps: [
      'Pela la zanahoria y córtala en dados muy pequeños. Lava el calabacín y córtalo también en dados pequeños.',
      'Pon las verduras en la cazuela y cubre con agua o caldo casero sin sal.',
      'Lleva a ebullición y cuece 10-12 minutos, hasta que la zanahoria empiece a ablandarse.',
      'Añade los fideos finos y cuece 4-5 minutos más (o el tiempo que indique el paquete), removiendo de vez en cuando para que no se peguen.',
      'Comprueba que tanto la verdura como los fideos estén blandos, sin partes duras.',
      'Retira del fuego y deja templar unos minutos: la sopa retiene mucho calor y puede quemar aunque parezca templada por fuera.',
      'Antes de servir, remueve bien y comprueba la temperatura tocando una cucharada con el labio o la muñeca.',
    ],
    tips: [
      'Los fideos calientes pueden quemar por dentro aunque el plato parezca templado: remueve y deja reposar un par de minutos más de lo que creas necesario.',
      'Los fideos llevan gluten: si es la primera vez que tu bebé lo prueba, empieza con una ración pequeña.',
    ],
  },
  { id: 'r19', name: 'Tortilla francesa con calabacín', mealTypes: ['cena'], minAgeIdx: 2, allergens: ['huevo'], time: 10, texture: 'finger', foodGroups: ['proteina', 'verduras'],
    ingredients: [
      { name: 'Huevo', quantity: '1 unidad' },
      { name: 'Calabacín', quantity: '1/2 calabacín pequeño, rallado' },
    ],
    utensils: ['Rallador', 'Bol', 'Sartén antiadherente', 'Espátula'],
    steps: [
      'Ralla el calabacín con un rallador de agujero grueso.',
      'Escurre el calabacín rallado presionándolo con las manos o con papel de cocina, para eliminar el exceso de agua.',
      'Casca el huevo en un bol, comprobando que no caiga nada de cáscara, y bátelo bien con un tenedor.',
      'Mezcla el calabacín escurrido con el huevo batido.',
      'Calienta una sartén antiadherente a fuego bajo con una gota de aceite. Vierte la mezcla extendiéndola en una capa fina.',
      'Cocina 3 minutos por un lado y dale la vuelta con ayuda de un plato; cocina 2-3 minutos más por el otro lado, hasta que el centro esté totalmente cuajado.',
      'Deja templar sobre una tabla y corta en tiras del grosor de un dedo para que tu bebé pueda sujetarlas.',
    ],
    tips: [
      'Comprueba siempre que no quede huevo líquido en el centro antes de servir.',
      'Este plato lleva huevo: si es la primera vez que lo prueba, ofrece una cantidad pequeña y obsérvalo durante las horas siguientes.',
    ],
  },
  { id: 'r20', name: 'Puré de boniato y guisantes', mealTypes: ['cena'], minAgeIdx: 0, allergens: [], time: 25, texture: 'pure', foodGroups: ['verduras', 'legumbres'],
    ingredients: [
      { name: 'Boniato', quantity: '1 unidad pequeña (unos 150 g)' },
      { name: 'Guisantes', quantity: '3 cucharadas (frescos o congelados)' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Cazuela', 'Batidora de mano', 'Tabla y cuchillo'],
    steps: [
      'Pela el boniato y córtalo en dados.',
      'Ponlo en la cazuela y cubre con agua sin sal. Lleva a ebullición y cuece 15 minutos.',
      'Añade los guisantes (frescos o congelados, no hace falta descongelarlos antes) y cuece 5 minutos más, hasta que el boniato se deshaga al pincharlo y los guisantes estén blandos.',
      'Escurre reservando un poco del agua de cocción.',
      'Tritura todo junto con el aceite de oliva hasta conseguir una crema homogénea, añadiendo agua reservada si queda demasiado espesa.',
      'Si tu bebé aún no tolera la piel de los guisantes, pasa el puré por un colador fino después de triturar.',
      'Deja templar antes de servir.',
    ],
    tips: ['El boniato es naturalmente dulce, así que este puré suele gustar mucho a los bebés que empiezan con la alimentación complementaria.'],
  },
  { id: 'r21', name: 'Pollo desmenuzado con puré de zanahoria', mealTypes: ['cena'], minAgeIdx: 1, allergens: [], time: 30, texture: 'trocitos', foodGroups: ['proteina', 'verduras'],
    ingredients: [
      { name: 'Pechuga de pollo', quantity: '1 filete (unos 80 g)' },
      { name: 'Zanahoria', quantity: '1 unidad, pelada' },
      { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' },
    ],
    utensils: ['Dos cazuelas (o una, si las cueces por turnos)', 'Batidora de mano', 'Dos tenedores para desmenuzar'],
    steps: [
      'Pon la pechuga de pollo entera (o en trozos grandes) en una cazuela y cubre con agua sin sal.',
      'Lleva a ebullición, baja el fuego y cuece 20-25 minutos, hasta que el pollo esté muy tierno y ya no tenga nada de color rosado por dentro.',
      'Mientras tanto, pela y corta la zanahoria en rodajas y cuécela en otra cazuela con agua sin sal 15 minutos, hasta que esté blanda al pinchar.',
      'Escurre la zanahoria y tritúrala con la batidora junto con el aceite de oliva hasta obtener un puré suave.',
      'Saca el pollo del agua y déjalo templar unos minutos para poder manipularlo sin quemarte.',
      'Desmenuza el pollo con dos tenedores (o con los dedos limpios) tirando en direcciones opuestas, hasta conseguir hilos finos, sin trozos grandes ni duros.',
      'Sirve el pollo desmenuzado junto al puré de zanahoria, mezclando un poco de puré con el pollo si tu bebé aún prefiere texturas más suaves.',
    ],
    tips: ['Desmenuzar el pollo mientras aún está tibio es mucho más fácil que cuando se enfría del todo.'],
  },
];

// ---------------------------------------------------------------------------
// 2. Ingredient database — one authored prep sentence + doneness cue per
//    ingredient, reused by every template that includes it.
// ---------------------------------------------------------------------------
const ING = {
  // verduras
  calabaza: { name: 'Calabaza', group: 'verduras', minAge: 0, allergens: [], quantity: '1/4 de calabaza pequeña, pelada y sin pepitas (unos 200 g)', prep: 'Pela la calabaza, retira las pepitas con una cuchara y córtala en dados de 2 cm.', cookTime: 15, doneCue: 'la calabaza se deshaga al pincharla con un tenedor' },
  patata: { name: 'Patata', group: 'verduras', minAge: 0, allergens: [], quantity: '1 patata mediana, pelada', prep: 'Pela la patata y córtala en dados de 2 cm.', cookTime: 15, doneCue: 'un tenedor atraviese la patata sin resistencia' },
  calabacin: { name: 'Calabacín', group: 'verduras', minAge: 0, allergens: [], quantity: '1/2 calabacín pequeño', prep: 'Lava el calabacín y córtalo en dados; no hace falta pelarlo si la piel está en buen estado.', cookTime: 12, doneCue: 'el calabacín se deshaga al pincharlo' },
  zanahoria: { name: 'Zanahoria', group: 'verduras', minAge: 0, allergens: [], quantity: '1 zanahoria, pelada', prep: 'Pela la zanahoria y córtala en rodajas finas.', cookTime: 15, doneCue: 'la zanahoria esté blanda al pinchar con un tenedor' },
  puerro: { name: 'Puerro', group: 'verduras', minAge: 0, allergens: [], quantity: '1/2 puerro (parte blanca y verde clara)', prep: 'Corta el puerro por la mitad a lo largo y lávalo bien separando las capas, ya que suele acumular tierra; corta la parte blanca y verde clara en rodajas finas.', cookTime: 18, doneCue: 'el puerro esté blando' },
  brocoli: { name: 'Brócoli', group: 'verduras', minAge: 1, allergens: [], quantity: '3-4 ramilletes pequeños', prep: 'Separa el brócoli en ramilletes pequeños y lávalos bien.', cookTime: 9, doneCue: 'el brócoli esté blando al pincharlo con un tenedor' },
  boniato: { name: 'Boniato', group: 'verduras', minAge: 0, allergens: [], quantity: '1 boniato pequeño (unos 150 g)', prep: 'Pela el boniato y córtalo en dados.', cookTime: 15, doneCue: 'el boniato se deshaga al pincharlo' },
  coliflor: { name: 'Coliflor', group: 'verduras', minAge: 1, allergens: [], quantity: '4-5 ramilletes pequeños', prep: 'Separa la coliflor en ramilletes pequeños y lávalos bien.', cookTime: 10, doneCue: 'la coliflor esté blanda al pincharla' },
  judiaVerde: { name: 'Judía verde', group: 'verduras', minAge: 1, allergens: [], quantity: 'Un puñado (unos 80 g)', prep: 'Lava las judías verdes, retira los extremos y los hilos laterales, y trocéalas.', cookTime: 12, doneCue: 'las judías verdes estén blandas' },
  espinacas: { name: 'Espinacas', group: 'verduras', minAge: 1, allergens: [], quantity: 'Un puñado de hojas frescas (unos 40 g)', prep: 'Lava bien las hojas de espinaca en agua fría, cambiando el agua un par de veces para arrastrar la tierra.', cookTime: 5, doneCue: 'las hojas se hayan reducido y estén blandas' },
  remolacha: { name: 'Remolacha cocida', group: 'verduras', minAge: 1, allergens: [], quantity: '1/2 remolacha pequeña, cocida', prep: 'Si la remolacha ya viene cocida al vacío, pélala (usa guantes: tiñe mucho) y trocéala.', cookTime: 5, doneCue: 'esté caliente' },
  tomate: { name: 'Tomate', group: 'verduras', minAge: 1, allergens: [], quantity: '1 tomate maduro pequeño', prep: 'Escalda el tomate unos segundos en agua hirviendo y pásalo por agua fría para pelarlo con facilidad; retira las semillas y trocéalo.', cookTime: 8, doneCue: 'el tomate se deshaga' },
  pimientoRojo: { name: 'Pimiento rojo', group: 'verduras', minAge: 2, allergens: [], quantity: '1/2 pimiento rojo', prep: 'Lava el pimiento, retira las semillas y las partes blancas internas, y córtalo en tiras finas.', cookTime: 10, doneCue: 'el pimiento esté blando' },
  chirivia: { name: 'Chirivía', group: 'verduras', minAge: 0, allergens: [], quantity: '1 chirivía pequeña, pelada', prep: 'Pela la chirivía y córtala en dados.', cookTime: 15, doneCue: 'la chirivía se deshaga al pincharla' },
  // frutas
  platano: { name: 'Plátano', group: 'frutas', minAge: 0, allergens: [], quantity: '1 unidad, bien madura', prep: 'Pela el plátano maduro (con alguna mancha en la piel: es más dulce y fácil de chafar).', rawOk: true, doneCue: '' },
  manzana: { name: 'Manzana', group: 'frutas', minAge: 0, allergens: [], quantity: '1 unidad', prep: 'Lava, pela y descorazona la manzana, y córtala en trozos.', cookTime: 10, doneCue: 'un cuchillo entre en la fruta sin resistencia' },
  pera: { name: 'Pera', group: 'frutas', minAge: 0, allergens: [], quantity: '1 unidad', prep: 'Lava, pela y descorazona la pera, y córtala en trozos.', cookTime: 8, doneCue: 'un cuchillo entre en la fruta sin resistencia' },
  melocoton: { name: 'Melocotón', group: 'frutas', minAge: 0, allergens: [], quantity: '1-2 unidades, maduras', prep: 'Escalda el melocotón unos segundos en agua hirviendo para pelarlo con facilidad, deshuésalo y trocéalo.', cookTime: 10, doneCue: 'el melocotón se deshaga' },
  aguacate: { name: 'Aguacate', group: 'grasas', minAge: 0, allergens: [], quantity: '1/2 unidad, madura', prep: 'Parte el aguacate maduro por la mitad, retira el hueso con cuidado y extrae la pulpa con una cuchara.', rawOk: true, doneCue: '' },
  mango: { name: 'Mango', group: 'frutas', minAge: 1, allergens: [], quantity: '1/2 unidad, madura', prep: 'Pela el mango y separa la pulpa del hueso central con un cuchillo.', rawOk: true, doneCue: '' },
  papaya: { name: 'Papaya', group: 'frutas', minAge: 1, allergens: [], quantity: '1/4 de papaya pequeña', prep: 'Corta la papaya por la mitad, retira las semillas negras con una cuchara y extrae la pulpa.', rawOk: true, doneCue: '' },
  ciruela: { name: 'Ciruela', group: 'frutas', minAge: 1, allergens: [], quantity: '2 unidades, maduras', prep: 'Lava la ciruela, deshuésala y trocéala.', cookTime: 8, doneCue: 'la ciruela se deshaga' },
  albaricoque: { name: 'Albaricoque', group: 'frutas', minAge: 1, allergens: [], quantity: '3 unidades, maduras', prep: 'Lava el albaricoque, deshuésalo y trocéalo.', cookTime: 8, doneCue: 'el albaricoque se deshaga' },
  kiwi: { name: 'Kiwi', group: 'frutas', minAge: 1, allergens: [], quantity: '1 unidad, madura', prep: 'Pela el kiwi y trocéalo.', rawOk: true, doneCue: '' },
  arandanos: { name: 'Arándanos', group: 'frutas', minAge: 1, allergens: [], quantity: 'Un puñado (unos 60 g)', prep: 'Lava bien los arándanos y aplástalos ligeramente con un tenedor: enteros pueden ser un riesgo de atragantamiento.', cookTime: 5, doneCue: 'se ablanden' },
  fresas: { name: 'Fresas', group: 'frutas', minAge: 1, allergens: [], quantity: '4-5 unidades, maduras', prep: 'Lava bien las fresas, retira las hojas verdes y trocéalas en cuartos.', rawOk: true, doneCue: '' },
  sandia: { name: 'Sandía', group: 'frutas', minAge: 1, allergens: [], quantity: '2 rodajas pequeñas', prep: 'Corta la sandía en trozos pequeños, retirando bien todas las pepitas.', rawOk: true, doneCue: '' },
  // legumbres
  lentejas: { name: 'Lentejas', group: 'legumbres', minAge: 1, allergens: [], quantity: '3 cucharadas soperas secas (unos 40 g)', prep: 'Lava las lentejas bajo el grifo en un colador hasta que el agua salga clara.', cookTime: 30, doneCue: 'las lentejas se deshagan al apretarlas entre los dedos' },
  lentejasRojas: { name: 'Lentejas rojas', group: 'legumbres', minAge: 0, allergens: [], quantity: '3 cucharadas (unos 40 g)', prep: 'Enjuaga las lentejas rojas en un colador; se cuecen rápido y no necesitan remojo.', cookTime: 20, doneCue: 'las lentejas rojas estén completamente deshechas' },
  garbanzos: { name: 'Garbanzos cocidos', group: 'legumbres', minAge: 1, allergens: [], quantity: '4 cucharadas (unos 80 g)', prep: 'Si usas garbanzos de bote, escúrrelos y enjuágalos bien para quitar el exceso de sal.', cookTime: 5, doneCue: 'los garbanzos estén calientes' },
  judiasBlancas: { name: 'Judías blancas cocidas', group: 'legumbres', minAge: 1, allergens: [], quantity: '4 cucharadas (unos 80 g)', prep: 'Escurre y enjuaga bien las judías blancas cocidas.', cookTime: 5, doneCue: 'las judías blancas estén calientes' },
  guisantes: { name: 'Guisantes', group: 'verduras', minAge: 0, allergens: [], quantity: '3 cucharadas (frescos o congelados)', prep: 'No hace falta descongelar los guisantes antes: se añaden directamente a la cazuela.', cookTime: 5, doneCue: 'los guisantes estén blandos' },
  // cereales
  arroz: { name: 'Arroz', group: 'cereales', minAge: 1, allergens: [], quantity: '3 cucharadas soperas (unos 40 g)', prep: 'Lava el arroz bajo el grifo hasta que el agua salga clara.', cookTime: 18, doneCue: 'el arroz esté tierno' },
  quinoa: { name: 'Quinoa', group: 'cereales', minAge: 1, allergens: [], quantity: '3 cucharadas (unos 40 g)', prep: 'Enjuaga bien la quinoa bajo el grifo para retirar su sabor amargo natural.', cookTime: 15, doneCue: 'los granos se vean translúcidos, con el germen separado' },
  cuscus: { name: 'Cuscús', group: 'cereales', minAge: 2, allergens: ['gluten'], quantity: '3 cucharadas (unos 30 g)', prep: 'Cubre el cuscús con la misma cantidad de agua o caldo hirviendo y tapa 5 minutos.', cookTime: 5, doneCue: 'haya absorbido todo el líquido' },
  fideosFinos: { name: 'Fideos finos', group: 'cereales', minAge: 2, allergens: ['gluten'], quantity: 'Un puñado pequeño (unos 30 g)', prep: 'Los fideos finos se cuecen directamente en el caldo o agua de la sopa.', cookTime: 5, doneCue: 'los fideos estén blandos' },
  panTierno: { name: 'Pan tierno', group: 'cereales', minAge: 2, allergens: ['gluten'], quantity: '1 rebanada, a poder ser integral', prep: 'Corta el pan en palitos de aproximadamente 1 cm de grosor.', rawOk: true, doneCue: '' },
  avena: { name: 'Avena', group: 'cereales', minAge: 0, allergens: [], quantity: '2 cucharadas de copos finos', prep: 'Los copos de avena no necesitan cocción: se ablandan al mezclarlos con líquido o fruta.', rawOk: true, doneCue: '' },
  // proteinas
  pollo: { name: 'Pechuga de pollo', group: 'proteina', minAge: 0, allergens: [], quantity: '1 filete pequeño (unos 60 g)', prep: 'Corta la pechuga de pollo en trozos pequeños, retirando cualquier resto de grasa o piel.', cookTime: 20, doneCue: 'el pollo esté blanco por dentro, sin ninguna parte rosada' },
  pavo: { name: 'Pechuga de pavo', group: 'proteina', minAge: 1, allergens: [], quantity: '1 filete pequeño (unos 60 g)', prep: 'Corta la pechuga de pavo en trozos pequeños, retirando cualquier resto de grasa.', cookTime: 18, doneCue: 'el pavo esté blanco por dentro, sin ninguna parte rosada' },
  ternera: { name: 'Ternera', group: 'proteina', minAge: 2, allergens: [], quantity: '60-70 g para guisar, en trozos pequeños', prep: 'Corta la ternera en trozos muy pequeños, retirando nervios o grasa visible.', cookTime: 35, doneCue: 'la ternera esté muy tierna y se deshaga con un tenedor' },
  merluza: { name: 'Merluza', group: 'proteina', minAge: 1, allergens: ['pescado'], quantity: '1 lomo pequeño, sin piel ni espinas visibles (unos 60 g)', prep: 'Cocina la merluza al vapor aparte y, con los dedos limpios, desmenúzala repasando bien cada trozo en busca de espinas antes de incorporarla.', cookTime: 7, doneCue: 'la merluza quede blanca y se separe en láminas' },
  pescadoBlanco: { name: 'Pescado blanco', group: 'proteina', minAge: 1, allergens: ['pescado'], quantity: '1 lomo pequeño, sin piel ni espinas visibles (unos 60 g)', prep: 'Cocina el pescado blanco al vapor aparte y, con los dedos limpios, desmenúzalo repasando bien cada trozo en busca de espinas antes de incorporarlo.', cookTime: 7, doneCue: 'el pescado quede opaco y se separe en láminas' },
  salmon: { name: 'Salmón', group: 'proteina', minAge: 1, allergens: ['pescado'], quantity: '1 lomo pequeño, sin piel ni espinas (unos 60 g)', prep: 'Cocina el salmón al vapor aparte y, con los dedos limpios, desmenúzalo repasando bien cada trozo en busca de espinas antes de incorporarlo.', cookTime: 8, doneCue: 'el salmón se separe en láminas con facilidad' },
  huevo: { name: 'Huevo', group: 'proteina', minAge: 2, allergens: ['huevo'], quantity: '1 unidad', prep: 'Casca el huevo en un bol, comprobando que no caiga nada de cáscara, y bátelo bien con un tenedor.', rawOk: true, doneCue: '' },
  // lacteos
  yogur: { name: 'Yogur natural sin azúcar', group: 'lacteos', minAge: 1, allergens: ['lacteos'], quantity: '1 unidad (125 g)', prep: 'Usa yogur natural sin azúcar ni edulcorantes añadidos.', rawOk: true, doneCue: '' },
  quesoFresco: { name: 'Queso fresco tipo Burgos', group: 'lacteos', minAge: 2, allergens: ['lacteos'], quantity: '30 g (un par de cucharadas)', prep: 'Escurre bien el queso fresco y chafalo con un tenedor.', rawOk: true, doneCue: '' },
};

// Grammatical gender/number per ingredient, so generated sentences use correct
// articles ("el"/"la"/"los"/"las"), object pronouns and adjective endings.
const ARTICLES = {
  calabaza: 'la', patata: 'la', calabacin: 'el', zanahoria: 'la', puerro: 'el', brocoli: 'el', boniato: 'el',
  coliflor: 'la', judiaVerde: 'la', espinacas: 'las', remolacha: 'la', tomate: 'el', pimientoRojo: 'el', chirivia: 'la',
  platano: 'el', manzana: 'la', pera: 'la', melocoton: 'el', aguacate: 'el', mango: 'el', papaya: 'la', ciruela: 'la',
  albaricoque: 'el', kiwi: 'el', arandanos: 'los', fresas: 'las', sandia: 'la',
  lentejas: 'las', lentejasRojas: 'las', garbanzos: 'los', judiasBlancas: 'las', guisantes: 'los',
  arroz: 'el', quinoa: 'la', cuscus: 'el', fideosFinos: 'los', panTierno: 'el', avena: 'la',
  pollo: 'la', pavo: 'la', ternera: 'la', merluza: 'la', pescadoBlanco: 'el', salmon: 'el', huevo: 'el',
  yogur: 'el', quesoFresco: 'el',
};
Object.keys(ING).forEach((k) => {
  const art = ARTICLES[k] || 'el';
  ING[k].article = art;
  ING[k].pronoun = art === 'el' ? 'lo' : art;
  ING[k].adjSuffix = (art === 'la' || art === 'las') ? 'a' : 'o';
  ING[k].plural = art === 'los' || art === 'las';
});
function artName(i) { return `${i.article} ${i.name.toLowerCase()}`; }
function artNames(items) { return joinNatural(items.map(artName)); }

const ACEITE = { name: 'Aceite de oliva virgen extra', quantity: '1 cucharadita' };

const ALLERGEN_TIP = {
  pescado: 'El pescado es un alérgeno frecuente: si es la primera vez que lo prueba, ofrécelo por la mañana y en poca cantidad, para poder observar cómo reacciona.',
  huevo: 'El huevo es un alérgeno frecuente: si es la primera vez que lo prueba, ofrece una cantidad pequeña y observa a tu bebé un par de horas.',
  gluten: 'Este plato lleva gluten: si es la primera vez que tu bebé lo prueba, empieza con una ración pequeña.',
  lacteos: 'Este plato lleva lácteos: si es la primera vez que tu bebé los prueba, empieza con una cantidad pequeña.',
};

function unique(arr) { return [...new Set(arr)]; }
function joinNatural(parts) {
  if (parts.length <= 1) return parts.join('');
  return `${parts.slice(0, -1).join(', ')} y ${parts[parts.length - 1]}`;
}
function combineDoneCues(items) {
  const cues = items.filter((i) => i.doneCue).map((i) => i.doneCue);
  if (!cues.length) return 'todo esté bien cocido y blando';
  return joinNatural(cues);
}
let genCounter = 0;
function nextId() { genCounter += 1; return `g${genCounter}`; }

function buildTipsFor(items, extra) {
  const allergens = unique(items.flatMap((i) => i.allergens || []));
  const tips = [...extra];
  allergens.forEach((a) => { if (ALLERGEN_TIP[a]) tips.push(ALLERGEN_TIP[a]); });
  return tips;
}

// ---- pure_hervido: any combo of verdura/legumbre/proteina, boiled + blended ----
function pureHervido({ mealType, items, extraTip }) {
  const names = items.map((i) => i.name);
  const ingredients = [...items.map((i) => ({ name: i.name, quantity: i.quantity })), ACEITE];
  const minAgeIdx = Math.max(0, ...items.map((i) => i.minAge));
  const allergens = unique(items.flatMap((i) => i.allergens || []));
  const foodGroups = unique(items.map((i) => i.group));
  const maxCook = Math.max(...items.map((i) => i.cookTime || 10));
  const steps = [
    ...items.map((i) => i.prep),
    `Pon ${artNames(items)} en la cazuela y cubre con agua fría sin sal. Lleva a ebullición y baja el fuego para que hierva suave.`,
    `Cuece unos ${maxCook} minutos, hasta que ${combineDoneCues(items)}.`,
    'Escurre con el colador, reservando un par de cucharadas del agua de cocción por si necesitas aclarar el puré después.',
    'Tritura con la batidora junto con el aceite de oliva, añadiendo agua reservada hasta lograr una crema suave y sin grumos.',
    'Deja templar y comprueba la temperatura antes de servir: debe estar tibio, nunca caliente.',
  ];
  return {
    id: nextId(),
    name: `Puré de ${joinNatural(names).toLowerCase()}`,
    mealTypes: [mealType], minAgeIdx, allergens, time: maxCook + 10, texture: 'pure', foodGroups,
    ingredients, utensils: ['Cazuela', 'Colador', 'Batidora de mano', 'Tabla y cuchillo'],
    steps,
    tips: buildTipsFor(items, [extraTip || 'Puedes preparar el doble de cantidad y congelar el resto en cubiteras; se conserva bien hasta 1 mes.']),
  };
}

// ---- pure_fruta: fruit-only puré, cooked and/or raw ----
function pureFruta({ items }) {
  const names = items.map((i) => i.name);
  const ingredients = items.map((i) => ({ name: i.name, quantity: i.quantity }));
  const minAgeIdx = Math.max(0, ...items.map((i) => i.minAge));
  const cookItems = items.filter((i) => !i.rawOk);
  const rawItems = items.filter((i) => i.rawOk);
  const maxCook = cookItems.length ? Math.max(...cookItems.map((i) => i.cookTime)) : 0;
  const steps = [...items.map((i) => i.prep)];
  if (cookItems.length) {
    steps.push(`Cuece ${artNames(cookItems)} al vapor (o con un par de cucharadas de agua en una cazuela) unos ${maxCook} minutos, hasta que ${combineDoneCues(cookItems)}.`);
    steps.push('Retira del fuego y deja templar unos minutos.');
  }
  if (rawItems.length && cookItems.length) {
    steps.push(`Añade ${artNames(rawItems)} (no necesita cocción) junto con la fruta ya cocida.`);
  }
  steps.push('Tritura con la batidora o chafa con un tenedor hasta obtener una compota fina y sin trozos.');
  steps.push('Si queda demasiado espesa, añade una cucharadita de agua.');
  const single = items.length === 1;
  return {
    id: nextId(),
    name: single ? `Compota de ${names[0].toLowerCase()}` : `Puré de ${joinNatural(names).toLowerCase()}`,
    mealTypes: ['merienda'], minAgeIdx, allergens: [], time: (maxCook || 5) + 10, texture: 'pure', foodGroups: unique(items.map((i) => i.group)),
    ingredients, utensils: cookItems.length ? ['Vaporera (o cazuela con cestillo)', 'Batidora de mano (o un tenedor)'] : ['Bol', 'Tenedor'],
    steps,
    tips: ['No hace falta añadir azúcar: la fruta ya tiene un sabor dulce natural.', 'Se conserva bien en la nevera 2 días en un recipiente cerrado, o congelada hasta 1 mes.'],
  };
}

// ---- yogur_fruta: yogurt + small soft fruit pieces, no cook (or light steam) ----
function yogurFruta({ items }) {
  const fruitNames = items.map((i) => i.name);
  const cookItems = items.filter((i) => !i.rawOk);
  const ingredients = [{ name: ING.yogur.name, quantity: ING.yogur.quantity }, ...items.map((i) => ({ name: i.name, quantity: i.quantity }))];
  const steps = [
    ...items.map((i) => i.prep),
  ];
  if (cookItems.length) {
    steps.push(`Cuece ${artNames(cookItems)} al vapor 5 minutos para ablandar la fruta antes de trocearla en piezas pequeñas y blandas.`);
  }
  steps.push('Corta la fruta en trozos muy pequeños y blandos, del tamaño que tu bebé pueda manejar sin riesgo.');
  steps.push('Pon el yogur natural sin azúcar añadido en un bol y mezcla con la fruta troceada.');
  steps.push('Sirve a temperatura ambiente, nunca recién sacado de la nevera, para que no esté demasiado frío.');
  return {
    id: nextId(),
    name: `Yogur con ${joinNatural(fruitNames).toLowerCase()}`,
    mealTypes: ['merienda'], minAgeIdx: Math.max(1, ...items.map((i) => i.minAge)), allergens: ['lacteos'], time: 10, texture: 'trocitos',
    foodGroups: unique(['lacteos', ...items.map((i) => i.group)]),
    ingredients, utensils: ['Tabla y cuchillo pequeño', 'Bol'],
    steps,
    tips: buildTipsFor([ING.yogur], ['Elige siempre yogur natural sin azúcar ni edulcorantes añadidos: los yogures "para niños" suelen llevar más azúcar del recomendado.']),
  };
}

// ---- tortitas: cereal + fruit + egg, small pancakes cut into strips ----
function tortitas({ cereal, fruit }) {
  const ingredients = [{ name: cereal.name, quantity: cereal.quantity }, { name: fruit.name, quantity: fruit.quantity }, { name: ING.huevo.name, quantity: ING.huevo.quantity }];
  return {
    id: nextId(),
    name: `Tortitas de ${cereal.name.toLowerCase()} y ${fruit.name.toLowerCase()}`,
    mealTypes: ['merienda'], minAgeIdx: 2, allergens: unique(['huevo', ...(cereal.allergens || [])]), time: 15, texture: 'finger',
    foodGroups: unique([cereal.group, fruit.group]),
    ingredients, utensils: ['Batidora (o un tenedor)', 'Bol', 'Sartén antiadherente', 'Espátula'],
    steps: [
      fruit.prep,
      ING.huevo.prep,
      cereal.prep,
      `Tritura ${cereal.name.toLowerCase()}, ${fruit.name.toLowerCase()} y el huevo juntos con la batidora hasta obtener una masa homogénea sin grumos grandes.`,
      'Calienta una sartén antiadherente a fuego bajo sin aceite (o con una gota si tiende a pegarse).',
      'Vierte pequeñas porciones de masa, una cucharada cada vez, para formar tortitas pequeñas.',
      'Cocina 2 minutos por un lado hasta que salgan burbujas en la superficie, dale la vuelta con la espátula y cocina 1-2 minutos más por el otro lado.',
      'Comprueba que el centro esté bien cuajado, sin masa líquida, antes de retirarlas del fuego.',
      'Deja enfriar sobre un plato y corta en tiras para que tu bebé las pueda coger con la mano.',
    ],
    tips: buildTipsFor([ING.huevo, cereal], ['Haz tortitas pequeñas, del tamaño de una cuchara sopera, para que se cocinen bien por dentro sin quemarse por fuera.']),
  };
}

// ---- palitos_untables: bread sticks + a mashable spread ----
function palitosUntables({ spreadName, spreadItems, prepSteps }) {
  const ingredients = [{ name: ING.panTierno.name, quantity: ING.panTierno.quantity }, ...spreadItems.map((i) => ({ name: i.name, quantity: i.quantity }))];
  return {
    id: nextId(),
    name: `Palitos de pan con ${spreadName.toLowerCase()}`,
    mealTypes: ['merienda'], minAgeIdx: 2, allergens: unique(['gluten', ...spreadItems.flatMap((i) => i.allergens || [])]), time: 5, texture: 'finger',
    foodGroups: unique(['cereales', ...spreadItems.map((i) => i.group)]),
    ingredients, utensils: ['Tabla y cuchillo', 'Bol', 'Tenedor'],
    steps: [
      ING.panTierno.prep + ' Así tu bebé puede sujetarlos bien con el puño.',
      ...prepSteps,
      `Unta generosamente cada palito de pan con la crema de ${spreadName.toLowerCase()} por todas las caras.`,
      'Sirve enseguida, recién untado.',
    ],
    tips: buildTipsFor(spreadItems, []),
  };
}

// ---- tortilla_finger: egg + grated vegetable ----
function tortillaFinger({ mealType, veg }) {
  const ingredients = [{ name: ING.huevo.name, quantity: ING.huevo.quantity }, { name: veg.name, quantity: `${veg.quantity}, rallad${veg.adjSuffix}` }];
  return {
    id: nextId(),
    name: `Tortilla de ${veg.name.toLowerCase()}`,
    mealTypes: [mealType], minAgeIdx: Math.max(2, veg.minAge), allergens: unique(['huevo', ...(veg.allergens || [])]), time: 15, texture: 'finger',
    foodGroups: unique(['proteina', veg.group]),
    ingredients, utensils: ['Rallador', 'Bol', 'Sartén antiadherente', 'Espátula'],
    steps: [
      `Lava ${artName(veg)} y rálla${veg.pronoun} con un rallador de agujero grueso.`,
      `Pon ${artName(veg)} rallad${veg.adjSuffix} en un colador o sobre papel de cocina y presiona para quitar el exceso de agua; así la tortilla no quedará blanda.`,
      ING.huevo.prep,
      `Mezcla ${artName(veg)} escurrid${veg.adjSuffix} con el huevo batido.`,
      'Calienta una gota de aceite en una sartén antiadherente a fuego medio-bajo. Vierte la mezcla y extiéndela para formar una tortilla fina.',
      'Cocina 3-4 minutos por un lado hasta que los bordes estén cuajados, dale la vuelta con ayuda de un plato y cocina 2-3 minutos más por el otro lado, hasta que el centro esté totalmente cuajado, sin huevo líquido.',
      'Deja templar sobre una tabla y corta en tiras del grosor de un dedo adulto, para que tu bebé pueda sujetarlas con el puño.',
    ],
    tips: buildTipsFor([ING.huevo], ['Comprueba siempre que el huevo esté completamente cuajado, sin partes líquidas, antes de servirlo.']),
  };
}

// ---- salteado_cereal: cereal + protein + vegetable(s), sautéed & chopped ----
function salteadoCereal({ cereal, protein, veggies }) {
  const ingredients = [{ name: cereal.name, quantity: cereal.quantity }, ...veggies.map((v) => ({ name: v.name, quantity: v.quantity })), { name: protein.name, quantity: protein.quantity }];
  const allergens = unique([...(cereal.allergens || []), ...(protein.allergens || []), ...veggies.flatMap((v) => v.allergens || [])]);
  return {
    id: nextId(),
    name: `${cereal.name} con ${joinNatural([...veggies.map((v) => v.name.toLowerCase()), protein.name.toLowerCase()])}`,
    mealTypes: ['comida'], minAgeIdx: Math.max(2, cereal.minAge, protein.minAge, ...veggies.map((v) => v.minAge)), allergens, time: 30, texture: 'trocitos',
    foodGroups: unique([cereal.group, protein.group, ...veggies.map((v) => v.group)]),
    ingredients, utensils: ['Cazuela para el cereal', 'Sartén con tapa', 'Colador', 'Tabla y cuchillo'],
    steps: [
      cereal.prep,
      `Cuece ${artName(cereal)} en agua sin sal siguiendo el tiempo del paquete (unos ${cereal.cookTime || 18} minutos). Escurre y reserva.`,
      `Mientras tanto, corta ${artName(protein)} en tiras finas y pela y corta ${artNames(veggies)} en dados muy pequeños (de menos de 1 cm).`,
      `Calienta un chorrito de aceite en una sartén y saltea ${artName(protein)} a fuego medio 5-6 minutos, removiendo, hasta que ${protein.doneCue}.`,
      `Añade ${artNames(veggies)} a la sartén con un par de cucharadas de agua, tapa y cocina hasta que ${combineDoneCues(veggies)}.`,
      `Mezcla ${artName(cereal)} ya cocid${cereal.adjSuffix} con ${artName(protein)} y las verduras en la sartén y remueve 1-2 minutos a fuego bajo para que se integren los sabores.`,
      'Con un tenedor, separa los granos y aplasta ligeramente las piezas más grandes para que sea fácil de masticar y tragar.',
      'Deja templar y sirve en trozos pequeños y blandos, comprobando que no haya piezas duras.',
    ],
    tips: buildTipsFor([cereal, protein, ...veggies], ['Si tu bebé todavía no mastica bien, puedes triturar ligeramente la mezcla con un tenedor en vez de dejarla entera.']),
  };
}

// ---- guiso_trocitos: meat + 2 vegetables, slow stew ----
function guisoTrocitos({ mealType, protein, veggies }) {
  const ingredients = [{ name: protein.name, quantity: protein.quantity }, ...veggies.map((v) => ({ name: v.name, quantity: v.quantity }))];
  return {
    id: nextId(),
    name: `${protein.name} guisad${protein.adjSuffix} con ${joinNatural(veggies.map((v) => v.name.toLowerCase()))}`,
    mealTypes: [mealType], minAgeIdx: Math.max(2, protein.minAge, ...veggies.map((v) => v.minAge)), allergens: unique([...(protein.allergens || []), ...veggies.flatMap((v) => v.allergens || [])]), time: 40, texture: 'trocitos',
    foodGroups: unique([protein.group, ...veggies.map((v) => v.group)]),
    ingredients, utensils: ['Cazuela u olla', 'Tabla y cuchillo'],
    steps: [
      `Corta ${artName(protein)} en trozos muy pequeños, del tamaño de un guisante grande, retirando cualquier nervio o grasa visible.`,
      `Calienta un chorrito de aceite de oliva en la cazuela y sofríe ${artName(protein)} a fuego medio 3-4 minutos, removiendo, hasta que cambie de color por fuera.`,
      ...veggies.map((v) => v.prep),
      `Añade ${artNames(veggies)} a la cazuela y cubre con agua sin sal hasta que todo quede cubierto.`,
      'Tapa y cocina a fuego lento 30 minutos, removiendo de vez en cuando y añadiendo un poco más de agua si se queda seco.',
      `Comprueba que ${artName(protein)} esté muy tiern${protein.adjSuffix} deshaciéndose con un tenedor; si aún está dur${protein.adjSuffix}, dale 10-15 minutos más a fuego bajo.`,
      'Deja templar y, si tu bebé empieza con trocitos, aplasta ligeramente cada pieza con el tenedor para facilitar la masticación.',
    ],
    tips: buildTipsFor([protein, ...veggies], ['Cocinar el guiso muy despacio, a fuego bajo, hace que la carne quede más tierna y fácil de masticar.']),
  };
}

// ---- sopa_trocitos: broth + starch + vegetables ----
function sopaTrocitos({ starch, veggies }) {
  const ingredients = [{ name: starch.name, quantity: starch.quantity }, ...veggies.map((v) => ({ name: v.name, quantity: v.quantity }))];
  return {
    id: nextId(),
    name: `Sopa de ${starch.name.toLowerCase()} con ${joinNatural(veggies.map((v) => v.name.toLowerCase()))}`,
    mealTypes: ['cena'], minAgeIdx: Math.max(2, starch.minAge, ...veggies.map((v) => v.minAge)), allergens: unique([...(starch.allergens || []), ...veggies.flatMap((v) => v.allergens || [])]), time: 20, texture: 'trocitos',
    foodGroups: unique([starch.group, ...veggies.map((v) => v.group)]),
    ingredients, utensils: ['Cazuela', 'Tabla y cuchillo'],
    steps: [
      ...veggies.map((v) => v.prep),
      `Pon ${artNames(veggies)} en la cazuela y cubre con agua o caldo casero sin sal.`,
      `Lleva a ebullición y cuece 10-12 minutos, hasta que empiecen a ablandarse.`,
      `Añade ${artName(starch)} y cuece unos ${starch.cookTime || 5} minutos más (o el tiempo que indique el paquete), removiendo de vez en cuando para que no se pegue.`,
      'Comprueba que tanto la verdura como el cereal estén blandos, sin partes duras.',
      'Retira del fuego y deja templar unos minutos: la sopa retiene mucho calor y puede quemar aunque parezca templada por fuera.',
      'Antes de servir, remueve bien y comprueba la temperatura tocando una cucharada con el labio o la muñeca.',
    ],
    tips: buildTipsFor([starch, ...veggies], ['Los líquidos calientes pueden quemar por dentro aunque el plato parezca templado: remueve y deja reposar un par de minutos más de lo que creas necesario.']),
  };
}

// ---- desmenuzado: shredded meat + vegetable purée served together ----
function desmenuzado({ protein, veg }) {
  const ingredients = [{ name: protein.name, quantity: protein.quantity.replace('60 g', '80 g') }, { name: veg.name, quantity: veg.quantity }, ACEITE];
  return {
    id: nextId(),
    name: `${protein.name} desmenuzad${protein.adjSuffix} con puré de ${veg.name.toLowerCase()}`,
    mealTypes: ['cena'], minAgeIdx: Math.max(1, protein.minAge, veg.minAge), allergens: unique([...(protein.allergens || []), ...(veg.allergens || [])]), time: 30, texture: 'trocitos',
    foodGroups: unique([protein.group, veg.group]),
    ingredients, utensils: ['Dos cazuelas (o una, cociendo por turnos)', 'Batidora de mano', 'Dos tenedores para desmenuzar'],
    steps: [
      `Pon ${artName(protein)} enter${protein.adjSuffix} (o en trozos grandes) en una cazuela y cubre con agua sin sal.`,
      `Lleva a ebullición, baja el fuego y cuece 20-25 minutos, hasta que ${protein.doneCue}.`,
      veg.prep,
      `Cuece ${artName(veg)} en otra cazuela con agua sin sal unos ${veg.cookTime} minutos, hasta que ${veg.doneCue}.`,
      `Escurre ${artName(veg)} y tritúra${veg.pronoun} con la batidora junto con el aceite de oliva hasta obtener un puré suave.`,
      `Saca ${artName(protein)} del agua y déja${protein.pronoun} templar unos minutos para poder manipular${protein.pronoun} sin quemarte.`,
      'Desmenuza con dos tenedores (o con los dedos limpios) tirando en direcciones opuestas, hasta conseguir hilos finos, sin trozos grandes ni duros.',
      `Sirve junto al puré de ${veg.name.toLowerCase()}, mezclando un poco si tu bebé aún prefiere texturas más suaves.`,
    ],
    tips: buildTipsFor([protein, veg], ['Desmenuzar la carne mientras aún está tibia es mucho más fácil que cuando se enfría del todo.']),
  };
}

// ---------------------------------------------------------------------------
// 3. Explicit, hand-picked combinations (realistic pairings, not random)
// ---------------------------------------------------------------------------
const generated = [];

// pure_hervido — comida
[
  ['boniato', 'pollo'], ['chirivia', 'patata'], ['judiaVerde', 'patata', 'pollo'],
  ['espinacas', 'patata', 'pescadoBlanco'], ['calabaza', 'garbanzos'], ['zanahoria', 'judiasBlancas'],
  ['puerro', 'boniato'], ['brocoli', 'patata', 'pavo'], ['coliflor', 'zanahoria', 'pollo'],
  ['remolacha', 'patata', 'pollo'], ['pimientoRojo', 'patata', 'pollo'], ['chirivia', 'zanahoria', 'ternera'],
  ['espinacas', 'garbanzos'], ['calabacin', 'garbanzos'], ['boniato', 'judiasBlancas'],
  ['brocoli', 'salmon', 'patata'], ['calabaza', 'pavo'], ['judiaVerde', 'merluza', 'patata'],
  ['coliflor', 'lentejasRojas'], ['zanahoria', 'lentejas', 'chirivia'],
  ['espinacas', 'boniato', 'pavo'], ['pimientoRojo', 'calabacin', 'pollo'], ['remolacha', 'zanahoria', 'garbanzos'],
  ['chirivia', 'boniato', 'pollo'], ['brocoli', 'coliflor', 'pollo'], ['calabaza', 'zanahoria', 'pavo'],
  ['puerro', 'patata', 'merluza'], ['judiaVerde', 'zanahoria', 'pavo'],
].forEach(([...keys]) => generated.push(pureHervido({ mealType: 'comida', items: keys.map((k) => ING[k]) })));

// pure_hervido — cena
[
  ['coliflor', 'patata'], ['espinacas', 'patata', 'merluza'], ['calabacin', 'boniato'],
  ['zanahoria', 'lentejasRojas'], ['chirivia', 'guisantes'], ['judiaVerde', 'patata', 'pavo'],
  ['calabaza', 'judiasBlancas'], ['boniato', 'zanahoria', 'pollo'], ['puerro', 'judiasBlancas'],
  ['calabaza', 'puerro'], ['coliflor', 'brocoli', 'pavo'], ['zanahoria', 'garbanzos'],
  ['boniato', 'espinacas', 'pollo'], ['chirivia', 'patata', 'pavo'], ['remolacha', 'boniato'],
  ['pimientoRojo', 'zanahoria', 'pollo'], ['calabacin', 'guisantes', 'merluza'], ['puerro', 'zanahoria', 'ternera'],
].forEach((keys) => generated.push(pureHervido({ mealType: 'cena', items: keys.map((k) => ING[k]) })));

// pure_fruta — merienda
[
  ['pera', 'melocoton'], ['manzana', 'ciruela'], ['melocoton', 'albaricoque'], ['pera', 'kiwi'],
  ['manzana', 'mango'], ['ciruela', 'pera'], ['albaricoque', 'manzana'], ['melocoton', 'pera', 'manzana'],
  ['mango'], ['papaya'], ['aguacate', 'platano'], ['platano', 'manzana'], ['kiwi', 'pera'],
  ['arandanos', 'manzana'], ['sandia'],
  ['ciruela', 'melocoton'], ['papaya', 'platano'], ['fresas', 'manzana'], ['albaricoque', 'pera'],
  ['kiwi', 'manzana'], ['mango', 'pera'],
].forEach((keys) => generated.push(pureFruta({ items: keys.map((k) => ING[k]) })));

// yogur_fruta — merienda
[['platano'], ['melocoton'], ['fresas'], ['mango'], ['kiwi'], ['arandanos'], ['papaya'], ['ciruela'],
  ['fresas', 'platano'], ['manzana', 'pera'], ['mango', 'fresas'], ['melocoton', 'arandanos']]
  .forEach((keys) => generated.push(yogurFruta({ items: keys.map((k) => ING[k]) })));

// tortitas — merienda
[['quinoa', 'platano'], ['avena', 'manzana'], ['avena', 'pera'], ['cuscus', 'platano'], ['quinoa', 'melocoton'],
  ['avena', 'ciruela'], ['quinoa', 'pera'], ['cuscus', 'manzana']]
  .forEach(([c, f]) => generated.push(tortitas({ cereal: ING[c], fruit: ING[f] })));

// palitos_untables — merienda
generated.push(palitosUntables({ spreadName: 'plátano chafado', spreadItems: [ING.platano], prepSteps: ['Chafa el plátano maduro con un tenedor hasta obtener una crema sin grumos grandes.'] }));
generated.push(palitosUntables({ spreadName: 'queso fresco', spreadItems: [ING.quesoFresco], prepSteps: ['Escurre bien el queso fresco y chafalo con un tenedor hasta que quede cremoso.'] }));
generated.push(palitosUntables({ spreadName: 'aguacate y plátano', spreadItems: [ING.aguacate, ING.platano], prepSteps: [ING.aguacate.prep, 'Chafa el aguacate junto con el plátano maduro con un tenedor hasta obtener una crema suave.'] }));
generated.push(palitosUntables({ spreadName: 'mango chafado', spreadItems: [ING.mango], prepSteps: ['Chafa la pulpa de mango con un tenedor hasta obtener una crema suave.'] }));

// tortilla_finger — only vegetables that make sense grated raw into an omelette
[['comida', 'zanahoria'], ['comida', 'boniato'], ['cena', 'calabaza'], ['cena', 'remolacha'],
  ['comida', 'chirivia'], ['cena', 'puerro']]
  .forEach(([meal, veg]) => generated.push(tortillaFinger({ mealType: meal, veg: ING[veg] })));

// salteado_cereal — comida
[
  { cereal: 'quinoa', protein: 'pollo', veggies: ['zanahoria', 'guisantes'] },
  { cereal: 'arroz', protein: 'pavo', veggies: ['brocoli'] },
  { cereal: 'cuscus', protein: 'pollo', veggies: ['calabacin'] },
  { cereal: 'quinoa', protein: 'pavo', veggies: ['judiaVerde'] },
  { cereal: 'arroz', protein: 'ternera', veggies: ['zanahoria'] },
  { cereal: 'quinoa', protein: 'pollo', veggies: ['pimientoRojo'] },
  { cereal: 'cuscus', protein: 'pavo', veggies: ['calabacin', 'zanahoria'] },
  { cereal: 'arroz', protein: 'pollo', veggies: ['guisantes', 'zanahoria'] },
  { cereal: 'quinoa', protein: 'salmon', veggies: ['brocoli'] },
  { cereal: 'cuscus', protein: 'ternera', veggies: ['pimientoRojo', 'calabacin'] },
].forEach(({ cereal, protein, veggies }) => generated.push(salteadoCereal({ cereal: ING[cereal], protein: ING[protein], veggies: veggies.map((v) => ING[v]) })));

// guiso_trocitos
[
  { mealType: 'comida', protein: 'pollo', veggies: ['zanahoria', 'patata'] },
  { mealType: 'cena', protein: 'pavo', veggies: ['calabacin', 'tomate'] },
  { mealType: 'cena', protein: 'ternera', veggies: ['boniato', 'zanahoria'] },
  { mealType: 'cena', protein: 'pollo', veggies: ['judiaVerde', 'patata'] },
  { mealType: 'comida', protein: 'ternera', veggies: ['pimientoRojo', 'zanahoria'] },
  { mealType: 'comida', protein: 'pavo', veggies: ['boniato', 'guisantes'] },
  { mealType: 'cena', protein: 'pollo', veggies: ['coliflor', 'zanahoria'] },
  { mealType: 'cena', protein: 'ternera', veggies: ['patata', 'guisantes'] },
].forEach(({ mealType, protein, veggies }) => generated.push(guisoTrocitos({ mealType, protein: ING[protein], veggies: veggies.map((v) => ING[v]) })));

// sopa_trocitos — cena
[
  { starch: 'quinoa', veggies: ['zanahoria', 'puerro'] },
  { starch: 'cuscus', veggies: ['calabacin', 'tomate'] },
  { starch: 'fideosFinos', veggies: ['brocoli', 'zanahoria'] },
  { starch: 'fideosFinos', veggies: ['guisantes', 'zanahoria'] },
  { starch: 'quinoa', veggies: ['calabacin', 'tomate'] },
  { starch: 'cuscus', veggies: ['zanahoria', 'guisantes'] },
  { starch: 'fideosFinos', veggies: ['puerro', 'zanahoria'] },
  { starch: 'arroz', veggies: ['calabaza', 'puerro'] },
].forEach(({ starch, veggies }) => generated.push(sopaTrocitos({ starch: ING[starch], veggies: veggies.map((v) => ING[v]) })));

// desmenuzado — cena
[['pavo', 'boniato'], ['pollo', 'calabaza'], ['ternera', 'patata'],
  ['pollo', 'chirivia'], ['pavo', 'zanahoria'], ['ternera', 'boniato']]
  .forEach(([protein, veg]) => generated.push(desmenuzado({ protein: ING[protein], veg: ING[veg] })));

// ---------------------------------------------------------------------------
// 4. Assemble, sanity-check, write
// ---------------------------------------------------------------------------
// Real YouTube videos found via web search that clearly match the dish (never
// invented). Attached only where a genuinely relevant match was found — most
// recipes intentionally have none, per "cuando se pueda" (best-effort).
const VIDEO_LINKS = {
  r1: { videoUrl: 'https://www.youtube.com/watch?v=6r_IwdTSLc8', videoTitle: 'Puré o crema de calabaza, zanahoria y patata para bebés' },
  r2: { videoUrl: 'https://www.youtube.com/watch?v=JCpMXuUxvM4', videoTitle: 'Puré de lentejas para bebés' },
  r3: { videoUrl: 'https://www.youtube.com/watch?v=VGc94Kq16xo', videoTitle: 'Crema de calabacín con pollo' },
  r4: { videoUrl: 'https://www.youtube.com/watch?v=fNVJLNBXBNs', videoTitle: 'Potito casero de verduras, arroz y pollo para bebés' },
  r5: { videoUrl: 'https://www.youtube.com/watch?v=lPTCRc6EuYs', videoTitle: 'Puré para bebés de garbanzos, calabaza, patata, pollo y zanahoria' },
  r6: { videoUrl: 'https://www.youtube.com/watch?v=OI-MUt3viAw', videoTitle: 'Puré de verduras con merluza para bebés' },
  r7: { videoUrl: 'https://www.youtube.com/watch?v=5ovRxjBsDUQ', videoTitle: 'Ternera guisada en olla exprés' },
  r9: { videoUrl: 'https://www.youtube.com/watch?v=cnsiLIPpyIU', videoTitle: 'Crema de lentejas rojas y calabaza' },
  r10: { videoUrl: 'https://www.youtube.com/watch?v=jXl1smn0yBM', videoTitle: 'Papilla de avena y plátano para bebés a partir de 6 meses' },
  r11: { videoUrl: 'https://www.youtube.com/watch?v=wFG0roT2rvU', videoTitle: 'Yogur con frutas: un postre saludable para bebés' },
  r12: { videoUrl: 'https://www.youtube.com/watch?v=TLDJLT-jA6I', videoTitle: 'Tortitas de avena y plátano' },
  r13: { videoUrl: 'https://www.youtube.com/watch?v=YYf_oecEpyA', videoTitle: 'Cómo hacer puré de pera con manzana para bebés' },
  r15: { videoUrl: 'https://www.youtube.com/watch?v=PA17R8ZtWxk', videoTitle: 'Compota para bebés: melocotón' },
  r16: { videoUrl: 'https://www.youtube.com/watch?v=Sl2A7HWlYQw', videoTitle: 'Crema de puerro y patata: receta fácil y rápida' },
  r17: { videoUrl: 'https://www.youtube.com/watch?v=nc1IDfZusaY', videoTitle: 'Potito de pescado, arroz y verdura para bebé' },
  r18: { videoUrl: 'https://www.youtube.com/watch?v=qsjsXk2Qbhg', videoTitle: 'Sopa de fideos con verduras para niños' },
  r19: { videoUrl: 'https://www.youtube.com/watch?v=9XR9TzgWkBY', videoTitle: 'Tortilla francesa para bebés, tierna y esponjosa' },
  r20: { videoUrl: 'https://www.youtube.com/watch?v=jNtBZURC5FU', videoTitle: 'Puré de boniato o batata dulce para bebés' },
  r21: { videoUrl: 'https://www.youtube.com/watch?v=WJLQ_G8hnVQ', videoTitle: 'Papilla de pollo y zanahoria' },
  g43: { videoUrl: 'https://www.youtube.com/watch?v=a5tixnZTRdo', videoTitle: 'Papilla de aguacate y plátano para bebés de 8 meses' },
  g69: { videoUrl: 'https://www.youtube.com/watch?v=eSoUbPtTnAM', videoTitle: 'Quinoa con pollo y verduras' },
};

const ALL = [...HANDWRITTEN, ...generated].map((r) => (VIDEO_LINKS[r.id] ? { ...r, ...VIDEO_LINKS[r.id] } : r));

// sanity checks
const ids = new Set();
const names = new Set();
let dupIds = 0;
let dupNames = 0;
ALL.forEach((r) => {
  if (ids.has(r.id)) dupIds += 1;
  ids.add(r.id);
  if (names.has(r.name)) dupNames += 1;
  names.add(r.name);
  if (!r.ingredients.length) throw new Error(`${r.id} has no ingredients`);
  if (!r.steps.length) throw new Error(`${r.id} has no steps`);
  if (r.minAgeIdx < 0 || r.minAgeIdx > 3) throw new Error(`${r.id} bad minAgeIdx`);
});

console.log(`Total recipes: ${ALL.length} (handwritten: ${HANDWRITTEN.length}, generated: ${generated.length})`);
console.log(`Duplicate ids: ${dupIds}, duplicate names: ${dupNames}`);
const byMeal = { comida: 0, merienda: 0, cena: 0 };
ALL.forEach((r) => r.mealTypes.forEach((m) => { byMeal[m] += 1; }));
console.log('By meal type:', byMeal);

if (dupNames > 0) {
  const seen = new Set();
  ALL.forEach((r) => {
    if (seen.has(r.name)) console.log('DUPLICATE NAME:', r.name, r.id);
    seen.add(r.name);
  });
}

writeFileSync(new URL('../public/recipes.json', import.meta.url), JSON.stringify(ALL, null, 2));
console.log('Wrote public/recipes.json');
